/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Registro.Cliente;
import Registro.Factura;

/**
 *
 * @author danie
 */
public class FrameGenerarFactura extends javax.swing.JInternalFrame {

    static Principal principal;

    /**
     * Creates new form FrameRegistrarVenta
     */
    public FrameGenerarFactura() {
        initComponents();
        lblNombreCliente.setText("");
        lblCedula.setText("");
        lblDireccion.setText("");
        lblTelefono.setText("");
    }

    public FrameGenerarFactura(Principal principal) {
        this.principal = principal;
        initComponents();
        
        
    }

    public void mostrarDatos() {
        lblNombreCliente.setText(principal.clienteActual.getNombres() +  principal.clienteActual.getApellidos());
        lblCedula.setText(principal.clienteActual.getCedula());
        lblDireccion.setText(principal.clienteActual.getDireccion());
        lblTelefono.setText(principal.clienteActual.getTelf());
        lblPrecioFinal.setText("$ " + String.format("%.2f", principal.ordenActual.calcularTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenerarFactura = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCine = new javax.swing.JLabel();
        lblRuc2 = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        Cedula1 = new javax.swing.JLabel();
        Cedula2 = new javax.swing.JLabel();
        Cedula3 = new javax.swing.JLabel();
        lblPrecioFinal = new javax.swing.JLabel();

        lblGenerarFactura.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblGenerarFactura.setText("FACTURA");

        lblNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreEmpresa.setText("Empresa:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cliente:");

        lblCine.setText("Star Cines");

        lblRuc2.setText("1768156470004");

        lblRuc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRuc.setText("RUC:");

        lblNombreCliente.setText("jLabel4");

        lblCedula.setText("jLabel5");

        lblDireccion.setText("jLabel6");

        lblTelefono.setText("jLabel7");

        Cedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cedula.setText("Cedula:");

        Cedula1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cedula1.setText("Direccion:");

        Cedula2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cedula2.setText("Telefono:");

        Cedula3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cedula3.setText("Precio Final:");

        lblPrecioFinal.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCine)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRuc2)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Cedula1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cedula)
                            .addComponent(Cedula2)
                            .addComponent(Cedula3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lblGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblGenerarFactura)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpresa)
                    .addComponent(lblCine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuc)
                    .addComponent(lblRuc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(Cedula))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula1)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula2)
                    .addComponent(lblTelefono))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula3)
                    .addComponent(lblPrecioFinal))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Cedula1;
    private javax.swing.JLabel Cedula2;
    private javax.swing.JLabel Cedula3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCine;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblGenerarFactura;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblPrecioFinal;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblRuc2;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables
}
