/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Products.*;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class FrameCompra extends javax.swing.JInternalFrame {

    static Principal principal;

    //String[] tamanioNachos = {"Grande", "Mediano"};
    /**
     * Creates new form FrameRegistrarVenta
     */
    public FrameCompra() {
        initComponents();
    }

    public FrameCompra(Principal principal) {
        this.principal = principal;
        initComponents();

        //Esconder Variables
        cmbDescripcion.setVisible(false);
        cmbTamanio.setVisible(false);
        lblDescripcion.setVisible(false);
        lblTamanio.setVisible(false);
        cmbTipoBebida.setVisible(false);
        lblTipoBebida.setVisible(false);
        lblCantidad.setVisible(false);
        lblNumeroCantidad.setVisible(false);
        btnCantidadMas.setVisible(false);
        btnCantidadMenos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTituloCompra = new javax.swing.JLabel();
        lblTipoProducto = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();
        txaMostrar = new javax.swing.JScrollPane();
        txaProductos = new javax.swing.JTextArea();
        cmbProducto = new javax.swing.JComboBox<>();
        cmbTamanio = new javax.swing.JComboBox<>();
        lblNumeroCantidad = new javax.swing.JLabel();
        btnCantidadMas = new javax.swing.JButton();
        btnCantidadMenos = new javax.swing.JButton();
        btnAnadirProducto = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        cmbDescripcion = new javax.swing.JComboBox();
        lblTipoBebida = new javax.swing.JLabel();
        cmbTipoBebida = new javax.swing.JComboBox<>();
        txtProductos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTamanio = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lblTituloCompra.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblTituloCompra.setText("COMPRA");

        lblTipoProducto.setText("Tipo de Producto");

        lblTamanio.setText("Tamaño");

        lblCantidad.setText("Cantidad");

        btnGenerarFactura.setText("Generar Factura");

        txaProductos.setColumns(20);
        txaProductos.setRows(5);
        txaMostrar.setViewportView(txaProductos);

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canguil", "Nacho", "HotDog", "Bebida" }));
        cmbProducto.setSelectedIndex(-1);
        cmbProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProductoItemStateChanged(evt);
            }
        });

        cmbTamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Normal", "Grande" }));
        cmbTamanio.setSelectedIndex(-1);
        cmbTamanio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTamanioItemStateChanged(evt);
            }
        });

        lblNumeroCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNumeroCantidad.setText("0");
        lblNumeroCantidad.setToolTipText("");

        btnCantidadMas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCantidadMas.setText("+");
        btnCantidadMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadMasActionPerformed(evt);
            }
        });

        btnCantidadMenos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCantidadMenos.setText("-");
        btnCantidadMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadMenosActionPerformed(evt);
            }
        });

        btnAnadirProducto.setText("Añadir al carrito");
        btnAnadirProducto.setEnabled(false);
        btnAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirProductoActionPerformed(evt);
            }
        });

        lblDescripcion.setText("Descripcion");
        lblDescripcion.setToolTipText("");

        cmbDescripcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chile", "Carne Molida" }));
        cmbDescripcion.setSelectedIndex(-1);

        lblTipoBebida.setText("Tipo de Bebida");

        cmbTipoBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vaso", "Botella" }));
        cmbTipoBebida.setSelectedIndex(-1);

        txtProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnadirProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarFactura))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTamanio)
                                    .addComponent(lblTipoProducto)
                                    .addComponent(lblCantidad)
                                    .addComponent(lblDescripcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCantidadMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(lblNumeroCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCantidadMas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbTamanio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel1)
                                                .addGap(7, 7, 7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipoBebida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloCompra)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txaMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(400, 400, 400))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloCompra)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoProducto)
                            .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTamanio)
                            .addComponent(cmbTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion)
                            .addComponent(cmbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipoBebida)
                                    .addComponent(cmbTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblCantidad))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNumeroCantidad)
                                .addComponent(btnCantidadMenos)
                                .addComponent(btnCantidadMas)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarFactura)
                    .addComponent(btnAnadirProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProductos)
                        .addComponent(txtTamanio))
                    .addComponent(txaMostrar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCantidadMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadMasActionPerformed
        // TODO add your handling code here:
        int nuevaCantidad = Integer.parseInt(lblNumeroCantidad.getText()) + 1;
        lblNumeroCantidad.setText(String.valueOf(nuevaCantidad));
    }//GEN-LAST:event_btnCantidadMasActionPerformed

    private void cmbProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProductoItemStateChanged
        // TODO add your handling code here:
        //Combobox Tamanio
        ComboBoxModel<String> tamanioNachos = new DefaultComboBoxModel((new String[]{
            "Grande", "Normal"}));
        ComboBoxModel<String> tamanioCanguil = new DefaultComboBoxModel((new String[]{
            "Grande", "Normal", "Pequeño"}));
        ComboBoxModel<String> tamanioHotDog = new DefaultComboBoxModel((new String[]{
            "Normal"}));
        ComboBoxModel<String> tamanioBebida = new DefaultComboBoxModel((new String[]{
            "Grande", "Normal", "Pequeña"}));

        //Combobox Extras
        ComboBoxModel<String> descripcionGeneral = new DefaultComboBoxModel((new String[]{
            "Chile", "Carne Molida"}));
        ComboBoxModel<String> descripcionBebida = new DefaultComboBoxModel((new String[]{
            "Coca-Cola", "Sprite", "Fanta"}));

        String opcionProducto = cmbProducto.getSelectedItem().toString();

        cmbTamanio.setSelectedIndex(-1);

        if (opcionProducto.equals("Canguil")) {
            cmbTamanio.setModel(tamanioCanguil);
            cmbTamanio.setVisible(true);
            cmbTamanio.setSelectedIndex(-1);
            lblTamanio.setVisible(true);
            cmbDescripcion.setModel(descripcionGeneral);
            cmbDescripcion.setVisible(false);
            lblDescripcion.setVisible(false);
            cmbTipoBebida.setVisible(false);
            lblTipoBebida.setVisible(false);
            lblCantidad.setVisible(true);
            lblNumeroCantidad.setVisible(true);
            btnCantidadMas.setVisible(true);
            btnCantidadMenos.setVisible(true);
            btnAnadirProducto.setEnabled(true);

        } else if (opcionProducto.equals("Nacho")) {
            cmbTamanio.setModel(tamanioNachos);
            cmbTamanio.setVisible(true);
            cmbTamanio.setSelectedIndex(-1);
            lblTamanio.setVisible(true);
            cmbDescripcion.setModel(descripcionGeneral);
            cmbDescripcion.setVisible(true);
            cmbDescripcion.setSelectedIndex(-1);
            lblDescripcion.setVisible(true);
            cmbTipoBebida.setVisible(false);
            lblTipoBebida.setVisible(false);
            lblCantidad.setVisible(true);
            lblNumeroCantidad.setVisible(true);
            btnCantidadMas.setVisible(true);
            btnCantidadMenos.setVisible(true);
            btnAnadirProducto.setEnabled(true);

        } else if (opcionProducto.equals("HotDog")) {
            cmbTamanio.setModel(tamanioHotDog);
            cmbTamanio.setVisible(false);
            cmbTamanio.setSelectedIndex(0);
            lblTamanio.setVisible(false);
            cmbDescripcion.setModel(descripcionGeneral);
            cmbDescripcion.setVisible(true);
            cmbDescripcion.setSelectedIndex(-1);
            lblDescripcion.setVisible(true);
            cmbTipoBebida.setVisible(false);
            lblTipoBebida.setVisible(false);
            lblCantidad.setVisible(true);
            lblNumeroCantidad.setVisible(true);
            btnCantidadMas.setVisible(true);
            btnCantidadMenos.setVisible(true);
            btnAnadirProducto.setEnabled(true);

        } else if (opcionProducto.equals("Bebida")) {
            cmbTamanio.setModel(tamanioBebida);
            cmbTamanio.setVisible(true);
            cmbTamanio.setSelectedIndex(-1);
            lblTamanio.setVisible(true);
            cmbDescripcion.setModel(descripcionBebida);
            cmbDescripcion.setVisible(true);
            cmbDescripcion.setSelectedIndex(-1);
            lblDescripcion.setVisible(true);
            cmbTipoBebida.setVisible(true);
            cmbTipoBebida.setSelectedIndex(-1);
            lblTipoBebida.setVisible(true);
            lblCantidad.setVisible(true);
            lblNumeroCantidad.setVisible(true);
            btnCantidadMas.setVisible(true);
            btnCantidadMenos.setVisible(true);
            btnAnadirProducto.setEnabled(true);
        }

    }//GEN-LAST:event_cmbProductoItemStateChanged

    private void cmbTamanioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTamanioItemStateChanged
        // TODO add your handling code here:
        if (cmbTamanio.isEnabled()) {
            btnCantidadMas.setEnabled(true);
            btnCantidadMenos.setEnabled(true);
        } else {
            btnCantidadMas.setEnabled(false);
            btnCantidadMenos.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTamanioItemStateChanged

    private void btnAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirProductoActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblNumeroCantidad.getText()) != 0) {
            String producto = cmbProducto.getSelectedItem().toString();
            String tamanio = cmbTamanio.getSelectedItem().toString();
            String extra = cmbDescripcion.getSelectedItem().toString();
            String extraTexto = "";
            double precio = 0;

            if (producto == "Canguil") {
                precio = (new Canguil(tamanio)).getPrecio();
            } else if (producto == "Bebida") {

            } else {
                Snack snack;
                if (producto == "Nacho") {
                    snack = new Nacho(tamanio);
                } else {
                    snack = new HotDog();
                }

                if (extra == "Chile") {
                    precio = (new Chile(snack)).getPrecio();
                    extraTexto = "con Chile";
                } else if (extra == "Carne Molida") {
                    precio = (new CarneMolida(snack)).getPrecio();
                    extraTexto = "con Carne Molida";
                } else {
                    precio = (snack).getPrecio();
                }
            }
            txaProductos.setText(txaProductos.getText().concat(producto)
                    + " " + tamanio + " " + extraTexto + "   " + String.format("%.2f", precio) + "\n");
            txtProductos.setText(txtProductos.getText().concat(producto) + "\n");

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se puede agregar"
                    + " el producto\nPor favor, ingrese una cantidad válida",
                    "Error", WIDTH, frameIcon);
        }
        lblNumeroCantidad.setText(String.valueOf(0));
    }//GEN-LAST:event_btnAnadirProductoActionPerformed

    private void btnCantidadMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadMenosActionPerformed
        // TODO add your handling code here:
        int nuevaCantidad = Integer.parseInt(lblNumeroCantidad.getText()) - 1;
        if (nuevaCantidad < 0) {
            lblNumeroCantidad.setText(String.valueOf(0));
        } else {
            lblNumeroCantidad.setText(String.valueOf(nuevaCantidad));
        }
    }//GEN-LAST:event_btnCantidadMenosActionPerformed

    //Método para limpiar todos los campos
    public void limpiarCasillas() {
        //txtCIReservacion.setText(null);
        //txtCodigoReservacion.setText(null);
        cmbProducto.setSelectedIndex(0);
        cmbTamanio.setSelectedIndex(0);
        //cmbAnio.setSelectedIndex(0);
        //txtISBNReservacion.setText(null);
    }

    //Método para limpiar el área de texto
    public void limpiarAreaDeTexto() {
        txaProductos.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirProducto;
    private javax.swing.JButton btnCantidadMas;
    private javax.swing.JButton btnCantidadMenos;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JComboBox cmbDescripcion;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbTamanio;
    private javax.swing.JComboBox<String> cmbTipoBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNumeroCantidad;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JLabel lblTipoBebida;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JLabel lblTituloCompra;
    private javax.swing.JScrollPane txaMostrar;
    private javax.swing.JTextArea txaProductos;
    private javax.swing.JTextField txtProductos;
    private javax.swing.JTextField txtTamanio;
    // End of variables declaration//GEN-END:variables
}
