/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author danie
 */
public class FrameMenu extends javax.swing.JInternalFrame {
    static Principal principal;
    /**
     * Creates new form FrameRegistrarVenta
     */
    public FrameMenu() {
        initComponents();
    }
    
    public FrameMenu(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCanguil = new javax.swing.JButton();
        btnNachos = new javax.swing.JButton();
        btnBebida = new javax.swing.JButton();
        btnHotDog = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("MENÚ");

        btnCanguil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCanguil.setText("Canguil");
        btnCanguil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanguilActionPerformed(evt);
            }
        });

        btnNachos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNachos.setText("Nachos");
        btnNachos.setMaximumSize(new java.awt.Dimension(91, 31));
        btnNachos.setMinimumSize(new java.awt.Dimension(91, 31));
        btnNachos.setPreferredSize(new java.awt.Dimension(91, 31));

        btnBebida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBebida.setText("Bebida");
        btnBebida.setMaximumSize(new java.awt.Dimension(91, 31));
        btnBebida.setMinimumSize(new java.awt.Dimension(91, 31));
        btnBebida.setPreferredSize(new java.awt.Dimension(91, 31));

        btnHotDog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHotDog.setText("HotDog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNachos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHotDog, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNachos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCanguil, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHotDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanguilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanguilActionPerformed
        
    }//GEN-LAST:event_btnCanguilActionPerformed

    //Método para limpiar el área de texto
    public void limpiarAreaDeTexto(){
        //txaMostrarCliente.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBebida;
    private javax.swing.JButton btnCanguil;
    private javax.swing.JButton btnHotDog;
    private javax.swing.JButton btnNachos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}