/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Products.Producto;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public
        class Principal extends javax.swing.JFrame {

    //Se debe indicar la cantidad máxima de libros de la biblioteca
    ArrayList<Producto> productos = new ArrayList<>();

    //Se declaran las instancias de las estructuras
    //ArregloLibros libros = new ArregloLibros(MAX_LIBROS);
    //ListaClientes clientes = new ListaClientes();
    //ColaReservaciones reservaciones = new ColaReservaciones();
    //Se inicializan las interfaces
    FrameCompra compra = new FrameCompra(this);
    FrameRegistrarCliente registrarCliente = new FrameRegistrarCliente(this);
    FrameCompra registrarReservacion = new FrameCompra(this);
    FrameBuscarReservacion eliminarReservacion = new FrameBuscarReservacion(this);
    FrameGenerarFactura registrarLibro = new FrameGenerarFactura(this);
    FrameGenerarFactura generarFacturas = new FrameGenerarFactura(this);

    public
            Principal() {
        initComponents();
        jCmbRegistro.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        ventanaPrincipal.add(compra);
        ventanaPrincipal.add(registrarCliente);
        ventanaPrincipal.add(registrarReservacion);
        ventanaPrincipal.add(eliminarReservacion);
        ventanaPrincipal.add(registrarLibro);
        ventanaPrincipal.add(generarFacturas);
//carga de imagenes
        this.setTitle("Cinema");
        ImageIcon imagenFondo = new ImageIcon("src\\img\\SistemaFondo_1.jpg");
        //jLabel1.setIcon(new ImageIcon(imagenFondo.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        btnCatalogo = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jCmbRegistro = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnClientes = new javax.swing.JMenu();
        btnConsultarClientes = new javax.swing.JMenuItem();
        btnRegistrarCliente = new javax.swing.JMenuItem();
        btnCatalogo1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCatalogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCatalogo.setText("Catálogo");
        btnCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        jCmbRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registro ", "Registro Cliente", "Registro Empleado", "Registro Orden", "Registro Factura", "Registro Venta" }));
        jCmbRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbRegistroActionPerformed(evt);
            }
        });

        ventanaPrincipal.setLayer(btnCatalogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ventanaPrincipal.setLayer(btnRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ventanaPrincipal.setLayer(jCmbRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaPrincipalLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnCatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro)
                    .addComponent(jCmbRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaPrincipalLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(jCmbRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatalogo))
                .addGap(189, 189, 189))
        );

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnClientes.setText("Registro");

        btnConsultarClientes.setText("Buscar");
        btnClientes.add(btnConsultarClientes);

        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        btnClientes.add(btnRegistrarCliente);

        jMenuBar1.add(btnClientes);

        btnCatalogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu (1).png"))); // NOI18N
        btnCatalogo1.setText("Catálogo");
        jMenuBar1.add(btnCatalogo1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        CentrarVentana(registrarCliente);
        registrarCliente.limpiarCasillas();
        registrarCliente.limpiarAreaDeTexto();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        jCmbRegistro.setVisible(true);
        btnRegistro.setVisible(false);

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        // TODO add your handling code here:
        CentrarVentana(compra);
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void jCmbRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbRegistroActionPerformed
        /*
 Registro 
Registro Cliente
Registro Empleado
Registro Orden
Registro Factura
Registro Venta*/

        int opcion = jCmbRegistro.getSelectedIndex();
        if (opcion == 0) {
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UNA OPCION");
        }
        else if (opcion == 1) {
            CentrarVentana(registrarCliente);
        }
        else if (opcion == 2) {

        }
    }//GEN-LAST:event_jCmbRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    void CentrarVentana(JInternalFrame frame) {
        cerrarVentanas();
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.width) / 2, (dimension.height - Dframe.height) / 2);
        frame.show();
    }

    void cerrarVentanas() {
        registrarCliente.setVisible(false);
        registrarReservacion.setVisible(false);
        eliminarReservacion.setVisible(false);
        registrarLibro.setVisible(false);
    }

    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JMenu btnCatalogo1;
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenuItem btnConsultarClientes;
    private javax.swing.JMenuItem btnRegistrarCliente;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jCmbRegistro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
